adapter: qlora
base_model: mistralai/Mistral-7B-v0.1
bf16: true
datasets:
- path: ./preproc_ds_chunked.jsonl
  type: completion
early_stopping_patience: 3
eval_batch_size: 4
eval_steps: 50
flash_attention: true
fp16: false
gpu_memory_limit: 78GiB
gradient_accumulation_steps: 8
gradient_checkpointing: true
group_by_length: true
learning_rate: 2e-4
load_in_4bit: true
lora_alpha: 64
lora_dropout: 0.05
lora_r: 32
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
max_grad_norm: 1.0
micro_batch_size: 4
optimizer: adamw_bnb_8bit
output_dir: ./outputs/lora-out-h100
pad_to_sequence_len: true
sample_packing: true
save_steps: 50
save_total_limit: 3
sdp_attention: true
sequence_len: 4096
strict: false
val_set_size: 0.05
warmup_ratio: 0.03
weight_decay: 0.01
